# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y1jRJvzhlUjdd66vnUOBj57YzwXHYc1s
"""

# app.py
# -*- coding: utf-8 -*-

import streamlit as st
import pandas as pd
import numpy as np
import yfinance as yf
from datetime import datetime, timedelta

# ===============================
# Streamlit 基本設定
# ===============================
st.set_page_config(page_title="台灣 ETF 個人化風險推薦", layout="wide")
st.title("📊 台灣 ETF 熱門排行 × Sharpe + θ-model 個人化推薦")

CACHE_TTL = 3600
TRADING_DAYS = 252
MARKET_TICKER = "0050.TW"   # 市場基準（CAPM）

# ===============================
# 1️⃣ TWSE ETF 成交量（HTML 穩定版）
# ===============================
@st.cache_data(ttl=CACHE_TTL)
def fetch_twse_etf_volume(days=3):
    results = []
    today = datetime.today()

    for i in range(1, days * 3 + 1):
        date = (today - timedelta(days=i)).strftime("%Y%m%d")
        url = f"https://www.twse.com.tw/exchangeReport/ETFDaily?date={date}"

        try:
            tables = pd.read_html(url)
            df = tables[0]
            df.columns = df.columns.get_level_values(-1)

            df = df[["證券代號", "成交股數"]]
            df["成交股數"] = (
                df["成交股數"]
                .astype(str)
                .str.replace(",", "")
                .astype(float)
            )

            results.append(df)

            if len(results) >= days:
                break
        except Exception:
            continue

    if not results:
        return pd.DataFrame()

    vol_df = pd.concat(results)

    return (
        vol_df
        .groupby("證券代號")["成交股數"]
        .mean()
        .reset_index()
        .rename(columns={"成交股數": "近N日平均成交量"})
        .sort_values("近N日平均成交量", ascending=False)
    )

# ===============================
# 2️⃣ Yahoo Finance ETF 資料
# ===============================
@st.cache_data(ttl=CACHE_TTL)
def fetch_etf_price_data(ticker):
    data = yf.download(ticker, period="1y", auto_adjust=True, progress=False)
    return data["Close"] if not data.empty else pd.Series()

# ===============================
# 3️⃣ Sharpe Ratio
# ===============================
def compute_sharpe(returns):
    if returns.std() == 0:
        return 0.0
    return (returns.mean() / returns.std()) * np.sqrt(TRADING_DAYS)

# ===============================
# 4️⃣ Beta（CAPM）
# ===============================
def compute_beta(asset_ret, market_ret):
    if market_ret.var() == 0:
        return 1.0
    return np.cov(asset_ret, market_ret)[0, 1] / market_ret.var()

# ===============================
# 5️⃣ θ-model（數據化、固定範圍）
# ===============================
def calculate_theta(age, horizon, loss_tol, reaction):
    """
    θ ∈ [-1, +1]
    """
    theta = 0
    theta += (40 - age) / 40 * 0.2
    theta += horizon / 30 * 0.3
    theta += loss_tol / 50 * 0.3
    theta += {"立即賣出": -0.2, "持有觀望": 0.0, "逢低加碼": 0.2}[reaction]
    return round(np.clip(theta, -1, 1), 2)

# ===============================
# 使用者輸入
# ===============================
st.subheader("👤 投資人風險設定")
c1, c2, c3, c4 = st.columns(4)
age = c1.slider("年齡", 20, 80, 35)
horizon = c2.slider("投資年限（年）", 1, 30, 10)
loss_tol = c3.slider("最大可接受損失 (%)", 0, 50, 15)
reaction = c4.radio("市場下跌 20% 時", ["立即賣出", "持有觀望", "逢低加碼"])

theta = calculate_theta(age, horizon, loss_tol, reaction)
st.info(f"🎯 投資人 θ 值 = {theta}")

# ===============================
# 主流程
# ===============================
if st.button("🚀 計算熱門 ETF × 個人化推薦"):

    # 1️⃣ 熱門 ETF（成交量）
    vol_df = fetch_twse_etf_volume(days=3)
    if vol_df.empty:
        st.error("⚠ 無法取得 TWSE 成交量資料，請稍後再試")
        st.stop()

    hot_etfs = vol_df.head(10)["證券代號"].tolist()
    hot_etfs = [f"{x}.TW" for x in hot_etfs]

    market_price = fetch_etf_price_data(MARKET_TICKER)
    market_ret = market_price.pct_change().dropna()

    records = []

    for etf in hot_etfs:
        price = fetch_etf_price_data(etf)
        if price.empty:
            continue

        ret = price.pct_change().dropna()

        sharpe = compute_sharpe(ret)
        beta = compute_beta(ret, market_ret)

        # 個人化風險距離（Sharpe 高 + Beta 接近 θ 偏好）
        personal_score = sharpe - abs(beta - (1 + theta))

        records.append({
            "ETF": etf,
            "Sharpe Ratio": round(sharpe, 2),
            "Beta": round(beta, 2),
            "個人化分數": round(personal_score, 3)
        })

    result_df = pd.DataFrame(records).sort_values("個人化分數", ascending=False)

    st.subheader("📈 熱門 ETF × 個人化推薦排序")
    st.dataframe(result_df, use_container_width=True)

st.caption("📌 資料來源：TWSE（HTML）、Yahoo Finance｜僅供研究與教學使用")
