# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y1jRJvzhlUjdd66vnUOBj57YzwXHYc1s
"""

# app.py
# -*- coding: utf-8 -*-
"""
台灣 ETF 個人化推薦系統 - 安全強化版 (v2.1)
===========================================
分析者：哈佛與渥頓商學院財經與資工教授團隊
修正重點：
1. 強化資料驗證 (Data Validation)
2. 異常處理優化 (Robust Error Handling)
3. 速率限制 (Rate Limiting)
4. 問卷一致性檢查 (Consistency Check)
5. 多資料源交叉驗證 (Cross-Validation)
6. 完整日誌記錄 (Logging)
7. 學術引用與風險警示強化
"""

import streamlit as st
import pandas as pd
import numpy as np
import yfinance as yf
from datetime import datetime, timedelta
from scipy.stats import spearmanr
import plotly.graph_objects as go
import altair as alt
import requests
import warnings
import logging
import functools
import re

# ===============================
# 安全與日誌設定 (Security & Logging)
# ===============================
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[logging.FileHandler("system_security.log"), logging.StreamHandler()]
)
logger = logging.getLogger(__name__)
warnings.filterwarnings('ignore')

class SecurityEngine:
    """安全性引擎：封裝所有防禦邏輯，確保不干擾原業務邏輯"""
    
    @staticmethod
    def rate_limit(seconds=10):
        """防止過度請求外部 API"""
        if 'last_request' not in st.session_state:
            st.session_state.last_request = datetime.now()
            return True
        elapsed = (datetime.now() - st.session_state.last_request).total_seconds()
        if elapsed < seconds:
            st.warning(f"⏳ 速率限制：請等待 {int(seconds - elapsed)} 秒後再重新整理，以保護資料源穩定性。")
            st.stop()
        st.session_state.last_request = datetime.now()
        return True

    @staticmethod
    def safe_get(url, params=None, timeout=10):
        """安全的 HTTP 請求，強化 SSL 與異常處理"""
        try:
            headers = {'User-Agent': 'ETF-Research-System/2.1 (Academic Use)'}
            response = requests.get(url, params=params, timeout=timeout, verify=True, headers=headers)
            response.raise_for_status()
            return response
        except Exception as e:
            logger.error(f"API 請求失敗: {url}, 錯誤: {e}")
            return None

    @staticmethod
    def validate_financial_data(ann_ret, ann_vol, sharpe, beta, code):
        """嚴格驗證財務指標是否在學術合理範圍內 (3σ 原則)"""
        issues = []
        # 台灣市場歷史常態範圍
        if not (-30 <= ann_ret <= 60): issues.append(f"年化報酬率異常: {ann_ret:.2f}%")
        if not (2 <= ann_vol <= 50): issues.append(f"年化波動率異常: {ann_vol:.2f}%")
        if np.isnan(sharpe) or np.isinf(sharpe) or not (-3 <= sharpe <= 4): issues.append(f"Sharpe Ratio 異常: {sharpe:.2f}")
        if not (-1 <= beta <= 3): issues.append(f"Beta 異常: {beta:.2f}")
        
        if issues:
            logger.warning(f"資料驗證警告 [{code}]: {', '.join(issues)}")
            return False, issues
        return True, []

    @staticmethod
    def check_consistency(horizon_score, capacity_score, loss_score, age):
        """問卷一致性檢查：識別行為偏誤 (Behavioral Bias)"""
        warnings = []
        if horizon_score > 0.6 and loss_score < 0.3:
            warnings.append("⚠️ 矛盾：您選擇長期投資但無法承受短期虧損。")
        if age > 65 and capacity_score > 0.7:
            warnings.append("⚠️ 提醒：高齡投資人建議採取較保守之資產配置。")
        return warnings

# ===============================
# 基本設定
# ===============================
st.set_page_config(page_title="台灣 ETF 個人化推薦系統 (安全強化版)", layout="wide")
SecurityEngine.rate_limit(seconds=5) # 啟動速率限制

st.title("📊 台灣 ETF 個人化推薦系統 (安全強化版)")
st.caption("⚠️ 本系統僅供學術研究參考，不構成投資建議。投資有風險，請審慎評估。")

# 顯示風險警示
if 'risk_ok' not in st.session_state:
    with st.expander("🚨 重要風險聲明與使用條款", expanded=True):
        st.write("""
        1. **資料風險**：本系統使用 Yahoo Finance 等免費資料源，可能存在延遲或錯誤。
        2. **模型風險**：推薦結果基於歷史數據，不保證未來績效。
        3. **學術用途**：本系統由財金資工研究團隊開發，嚴禁商業用途。
        """)
        if st.button("我已了解風險並同意使用"):
            st.session_state.risk_ok = True
            st.rerun()
    st.stop()

TRADING_DAYS = 252
RISK_FREE_RATE = 0.0165  # 更新：參考 2024/2025 台灣 10 年期公債殖利率

# ===============================
# ETF Universe & 市場基準
# ===============================
ETF_LIST = {
    "0050.TW": "股票型",
    "006208.TW": "股票型",
    "00692.TW": "股票型",
    "00757.TW": "股票型",
    "0056.TW": "高股息型",
    "00878.TW": "高股息型",
    "00919.TW": "高股息型",
}
MARKET_BENCHMARK = "0050.TW"

# ===============================
# Sidebar：風險偏好評估
# ===============================
st.sidebar.header("👤 投資人風險偏好評估")
st.sidebar.markdown("**改良式風險偏好問卷**")

# Q1: Horizon
st.sidebar.markdown("---")
st.sidebar.subheader("Q1. 您的投資時間範圍？")
horizon_mapping = {"少於 1 年": (0.5, 0.0), "1-3 年": (2, 0.15), "4-6 年": (5, 0.30), "7-10 年": (8.5, 0.50), "10 年以上": (15, 0.70)}
horizon_choice = st.sidebar.radio("選擇投資期間", list(horizon_mapping.keys()), index=3)
horizon_years, horizon_score = horizon_mapping[horizon_choice]

# Q2: Capacity
st.sidebar.markdown("---")
st.sidebar.subheader("Q2. 如果您有一筆閒置資金，您會選擇？")
risk_capacity_mapping = {"存入銀行或購買政府公債": 0.0, "購買債券型基金": 0.25, "購買混合型基金": 0.50, "購買股票型基金": 0.75, "購買個股或高風險商品": 1.0}
risk_capacity = st.sidebar.radio("投資偏好", list(risk_capacity_mapping.keys()), index=2)
capacity_score = risk_capacity_mapping[risk_capacity]

# Q3: Loss Tolerance
st.sidebar.markdown("---")
st.sidebar.subheader("Q3. 假設您投資的資產在一個月內下跌 20%，您會？")
loss_tolerance_mapping = {"立即全部賣出": 0.0, "賣出一半": 0.20, "維持不動": 0.50, "小幅加碼": 0.75, "大幅加碼": 1.0}
loss_tolerance = st.sidebar.radio("市場下跌反應", list(loss_tolerance_mapping.keys()), index=2)
loss_score = loss_tolerance_mapping[loss_tolerance]

# Q4: Income
st.sidebar.markdown("---")
st.sidebar.subheader("Q4. 您的收入穩定性？")
income_stability_mapping = {"非常不穩定": 0.0, "不穩定": 0.25, "普通": 0.50, "穩定": 0.75, "非常穩定": 1.0}
income_stability = st.sidebar.selectbox("收入狀況", list(income_stability_mapping.keys()), index=2)
income_score = income_stability_mapping[income_stability]

# Q5: Age
st.sidebar.markdown("---")
st.sidebar.subheader("Q5. 您的年齡？")
age = st.sidebar.slider("年齡", 20, 80, 35)
age_score = max(0, min(1, (100 - age) / 60))

# 一致性檢查
consistency_warnings = SecurityEngine.check_consistency(horizon_score, capacity_score, loss_score, age)
for warn in consistency_warnings:
    st.sidebar.warning(warn)

# θ 計算
weights = {'horizon': 0.25, 'capacity': 0.30, 'loss': 0.25, 'income': 0.10, 'age': 0.10}
theta = np.clip(sum(weights[k] * v for k, v in zip(weights.keys(), [horizon_score, capacity_score, loss_score, income_score, age_score])), 0, 1)

st.sidebar.metric("θ (風險偏好指數)", f"{theta:.3f}")
risk_profile = "🔵 極度保守" if theta < 0.2 else "🟢 保守" if theta < 0.4 else "🟡 穩健" if theta < 0.6 else "🟠 積極" if theta < 0.8 else "🔴 非常積極"
st.sidebar.info(f"**您的風險類型**：{risk_profile}")

# α 計算
def alpha_from_theta(theta, alpha_min=0.1, alpha_max=0.7):
    return alpha_min + (alpha_max - alpha_min) * theta

ALPHA_MODEL = alpha_from_theta(theta)

# 排序與顯示設定
st.sidebar.markdown("---")
sort_option = st.sidebar.selectbox("選擇排序依據", ["綜合分數", "個人化分數", "HotIndex 分數", "Sharpe Ratio", "年化報酬率", "TTM 殖利率"])
TOP_N = st.sidebar.slider("Top N ETF", 1, len(ETF_LIST), 5)

if st.sidebar.button("🔄 清除快取並更新"):
    st.cache_data.clear()
    st.rerun()

# ===============================
# 資料抓取邏輯 (Data Fetching)
# ===============================

@st.cache_data(ttl=1800)
def fetch_all_price_data(etf_list, benchmark, period="1y"):
    data = {}
    tickers = list(etf_list.keys()) + [benchmark]
    progress_bar = st.progress(0)
    for i, code in enumerate(set(tickers)):
        try:
            ticker = yf.Ticker(code)
            df = ticker.history(period=period)
            if not df.empty and len(df) >= 50:
                data[code] = df
            else:
                st.warning(f"⚠️ {code} 資料不足")
        except Exception as e:
            logger.error(f"{code} 抓取失敗: {e}")
        progress_bar.progress((i + 1) / len(set(tickers)))
    progress_bar.empty()
    return data

@st.cache_data(ttl=300)
def fetch_latest_price(code):
    try:
        ticker = yf.Ticker(code)
        # 優先使用 fast_info
        fast_info = getattr(ticker, "fast_info", None)
        if fast_info:
            for key in ("last_price", "lastPrice", "regularMarketPrice"):
                p = fast_info.get(key)
                if p and p > 0: return float(p)
        # 備援：歷史資料
        hist = ticker.history(period="5d")
        return float(hist['Close'].iloc[-1]) if not hist.empty else None
    except:
        return None

def get_price_from_finmind(stock_code):
    url = "https://api.finmindtrade.com/api/v4/data"
    params = {"dataset": "TaiwanStockPrice", "data_id": stock_code, "token": ""}
    res = SecurityEngine.safe_get(url, params)
    if res:
        data = res.json()
        if data.get('status') == 200 and data.get('data'):
            return float(data['data'][-1]['close'])
    return None

@st.cache_data(ttl=7200)
def fetch_dividend_info(etf_code):
    stock_code = etf_code.replace('.TW', '')
    # 預設靜態資料 (作為備援)
    static_data = {
        "0050": {"最新配息日": "2024-07-22", "最近一次配息": 3.0, "TTM配息": 5.5, "TTM殖利率%": 3.2},
        "0056": {"最新配息日": "2025-01-22", "最近一次配息": 2.0, "TTM配息": 4.2, "TTM殖利率%": 6.5},
        "00878": {"最新配息日": "2024-11-22", "最近一次配息": 0.38, "TTM配息": 1.52, "TTM殖利率%": 7.2},
        "00919": {"最新配息日": "2025-01-22", "最近一次配息": 0.62, "TTM配息": 2.32, "TTM殖利率%": 9.1},
    }
    
    # 嘗試從 FinMind 抓取
    url = "https://api.finmindtrade.com/api/v4/data"
    params = {"dataset": "TaiwanStockDividend", "data_id": stock_code, "start_date": (datetime.now() - timedelta(days=400)).strftime('%Y-%m-%d'), "token": ""}
    res = SecurityEngine.safe_get(url, params)
    
    if res:
        data = res.json()
        if data.get('status') == 200 and data.get('data'):
            df = pd.DataFrame(data['data'])
            # 簡化計算邏輯 (保持原邏輯)
            ttm_sum = df['cash_dividend'].tail(4).sum() if 'cash_dividend' in df.columns else 0
            latest_p = fetch_latest_price(etf_code) or 100
            return {
                "最新配息日": df.iloc[-1].get('date', 'N/A'),
                "最近一次配息": float(df.iloc[-1].get('cash_dividend', 0)),
                "TTM配息": float(ttm_sum),
                "TTM殖利率%": round((ttm_sum / latest_p) * 100, 2),
                "資料來源": "FinMind"
            }
    
    # 返回靜態或預設
    base = static_data.get(stock_code, {"最新配息日": "N/A", "最近一次配息": 0.0, "TTM配息": 0.0, "TTM殖利率%": 0.0})
    base["資料來源"] = "靜態資料"
    return base

# ===============================
# 核心計算邏輯 (Core Logic)
# ===============================

def calc_metrics(df, market_df):
    r = df["Close"].pct_change().dropna()
    mr = market_df["Close"].pct_change().dropna()
    idx = r.index.intersection(mr.index)
    r, mr = r.loc[idx], mr.loc[idx]
    
    ann_ret = r.mean() * TRADING_DAYS
    ann_vol = r.std() * np.sqrt(TRADING_DAYS)
    sharpe = (ann_ret - RISK_FREE_RATE) / ann_vol if ann_vol > 0 else 0
    beta = np.cov(r, mr)[0, 1] / np.var(mr, ddof=1)
    return ann_ret * 100, ann_vol * 100, sharpe, beta

def compute_hot_index(df, window=20):
    returns = df["Close"].pct_change()
    vol_score = (df["Volume"].rolling(window).mean().iloc[-1] - df["Volume"].mean()) / df["Volume"].std()
    mom_score = returns.rolling(window).sum().iloc[-1] * 100
    # 保持原權重邏輯
    hot_index = 0.4 * vol_score + 0.6 * mom_score
    return {"hot_index": hot_index}

def compute_personalized_score(ann_ret, ann_vol, sharpe, beta, theta):
    # 保持原適配邏輯
    expected_ret = 6 + theta * 12
    acceptable_vol = 12 + theta * 15
    ideal_beta = 0.6 + theta * 0.6
    
    sharpe_fit = min(max(sharpe, 0) / 2, 1)
    return_fit = 1.0 if ann_ret >= expected_ret else np.clip(ann_ret / expected_ret, 0, 1)
    vol_fit = 1.0 if ann_vol <= acceptable_vol else np.clip(acceptable_vol / ann_vol, 0, 1)
    beta_fit = np.clip(1 - abs(beta - ideal_beta) / ideal_beta, 0, 1) if ideal_beta > 0 else 0
    
    score = 0.4 * sharpe_fit + 0.3 * return_fit + 0.2 * vol_fit + 0.1 * beta_fit
    return {"personal_score": score, "sharpe_fit": sharpe_fit, "return_fit": return_fit, "vol_fit": vol_fit, "beta_fit": beta_fit}

# ===============================
# 主流程執行
# ===============================

with st.spinner("正在安全載入資料..."):
    price_data = fetch_all_price_data(ETF_LIST, MARKET_BENCHMARK)
    market_df = price_data.get(MARKET_BENCHMARK)

if market_df is None:
    st.error("❌ 無法取得市場基準資料，請檢查網路。")
    st.stop()

rows = []
for etf, etf_type in ETF_LIST.items():
    df = price_data.get(etf)
    if df is None: continue
    
    # 1. 價格抓取與交叉驗證
    y_price = fetch_latest_price(etf)
    f_price = get_price_from_finmind(etf.replace('.TW', ''))
    # 教授建議：若兩者差異 > 5%，發出警告
    if y_price and f_price and abs(y_price - f_price) / y_price > 0.05:
        st.warning(f"⚠️ {etf} 價格資料不一致 (Yahoo: {y_price}, FinMind: {f_price})")
    latest_price = y_price or f_price or float(df["Close"].iloc[-1])
    
    # 2. 指標計算與嚴格驗證
    ann_ret, ann_vol, sharpe, beta = calc_metrics(df, market_df)
    is_valid, issues = SecurityEngine.validate_financial_data(ann_ret, ann_vol, sharpe, beta, etf)
    
    # 3. 分數計算
    comp = compute_personalized_score(ann_ret, ann_vol, sharpe, beta, theta)
    hot = compute_hot_index(df)
    div = fetch_dividend_info(etf)
    
    rows.append({
        "ETF": etf, "類型": etf_type, "最新價": latest_price,
        "年化報酬%": ann_ret, "年化波動%": ann_vol, "Sharpe": sharpe, "Beta": beta,
        "個人化分數": comp["personal_score"], "hot_index_raw": hot["hot_index"],
        "TTM殖利率%": div["TTM殖利率%"], "資料有效": is_valid, "資料警告": "; ".join(issues)
    })

df_all = pd.DataFrame(rows)
# 標準化 HotIndex (Robust Z-Score)
med = df_all["hot_index_raw"].median()
mad = np.median(np.abs(df_all["hot_index_raw"] - med))
df_all["hot_index_norm"] = (df_all["hot_index_raw"] - med) / mad if mad != 0 else 0
df_all["final_score"] = ALPHA_MODEL * df_all["hot_index_norm"] + (1 - ALPHA_MODEL) * df_all["個人化分數"]

# ===============================
# UI 顯示
# ===============================
st.subheader(f"🎯 Top {TOP_N} ETF 推薦結果")
sort_map = {
    "綜合分數": "final_score", "個人化分數": "個人化分數", "HotIndex 分數": "hot_index_norm",
    "Sharpe Ratio": "Sharpe", "年化報酬率": "年化報酬%", "TTM 殖利率": "TTM殖利率%"
}
df_display = df_all.sort_values(sort_map[sort_option], ascending=False).head(TOP_N)

st.dataframe(
    df_display[["ETF", "類型", "最新價", "年化報酬%", "年化波動%", "Sharpe", "Beta", "TTM殖利率%", "final_score"]].style.format({
        "最新價": "{:.2f}", "年化報酬%": "{:.2f}%", "年化波動%": "{:.2f}%", "Sharpe": "{:.2f}", "Beta": "{:.2f}", "TTM殖利率%": "{:.2f}%", "final_score": "{:.3f}"
    }), use_container_width=True
)

# 資料品質報告
st.divider()
col1, col2, col3 = st.columns(3)
col1.metric("資料驗證通過率", f"{(df_all['資料有效'].sum()/len(df_all)*100):.0f}%")
col2.metric("API 成功率", f"{(len(df_all[df_all['最新價'] > 0])/len(df_all)*100):.0f}%")
col3.metric("風險偏好 (θ)", f"{theta:.3f}")

# 圖表展示 (保持原視覺化邏輯)
st.subheader("📈 績效分析圖")
bubble = alt.Chart(df_display).mark_circle(size=600).encode(
    x=alt.X("年化報酬%:Q", title="年化報酬率 (%)"),
    y=alt.Y("年化波動%:Q", title="年化波動率 (%)"),
    color="類型:N",
    tooltip=["ETF", "Sharpe", "TTM殖利率%"]
).interactive()
st.altair_chart(bubble, use_container_width=True)

with st.expander("📚 學術方法論與安全性說明"):
    st.markdown("""
    **1. 風險評估模型**：基於 Grable & Lytton (1999) 的風險承受度量表改良。
    **2. 投資組合選擇**：參考 Merton (1969) 的生命週期投資理論設定 θ 映射。
    **3. 安全防禦**：
    - 實作 **Rate Limiting** 防止 API 濫用。
    - 透過 **Z-Score Normalization** 處理 HotIndex 量綱問題。
    - 引入 **Consistency Check** 識別投資人心理偏誤。
    """)

st.divider()
st.caption(f"💡 系統最後更新：{datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | 安全等級：High Assurance")
