# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y1jRJvzhlUjdd66vnUOBj57YzwXHYc1s
"""

# -*- coding: utf-8 -*-
"""
台灣熱門 ETF 即時資訊儀表板
功能：即時報價、配息資訊、績效指標、視覺化圖表
"""

import streamlit as st
import pandas as pd
import numpy as np
import yfinance as yf
from datetime import datetime, timedelta
import plotly.graph_objects as go
import altair as alt
import requests
import warnings
warnings.filterwarnings('ignore')

# ===============================
# 基本設定
# ===============================
st.set_page_config(page_title="台灣熱門 ETF 資訊", layout="wide")
st.title("📊 台灣熱門 ETF 即時資訊")
st.caption("即時報價 | 配息資訊 | 績效分析 | 互動式圖表")

TRADING_DAYS = 252
RISK_FREE_RATE = 0.015

# ===============================
# ETF 清單
# ===============================
ETF_LIST = {
    "0050.TW": "元大台灣50",
    "006208.TW": "富邦台50",
    "00692.TW": "富邦公司治理",
    "00757.TW": "統一FANG+",
    "0056.TW": "元大高股息",
    "00878.TW": "國泰永續高股息",
    "00919.TW": "群益台灣精選高息",
    "00929.TW": "復華台灣科技優息"
}
MARKET_BENCHMARK = "0050.TW"

# ===============================
# Sidebar 設定
# ===============================
st.sidebar.header("⚙️ 顯示設定")

# ETF 選擇
selected_etfs = st.sidebar.multiselect(
    "選擇要顯示的 ETF",
    options=list(ETF_LIST.keys()),
    default=list(ETF_LIST.keys()),
    format_func=lambda x: f"{x.replace('.TW', '')} - {ETF_LIST[x]}"
)

# 排序選項
sort_option = st.sidebar.selectbox(
    "排序依據",
    ["Sharpe Ratio", "年化報酬率", "TTM 殖利率", "成交量", "最新價"]
)

# Top N 顯示
top_n = st.sidebar.slider("顯示前 N 檔", 3, len(ETF_LIST), 5)

st.sidebar.markdown("---")
if st.sidebar.button("🔄 重新載入資料"):
    st.cache_data.clear()
    st.rerun()

# ===============================
# 資料抓取函數
# ===============================

@st.cache_data(ttl=1800)
def fetch_price_data(etf_code, period="1y"):
    """抓取歷史價格資料"""
    try:
        ticker = yf.Ticker(etf_code)
        df = ticker.history(period=period)
        if not df.empty and len(df) >= 50:
            return df
        return None
    except:
        return None


@st.cache_data(ttl=300)
def fetch_latest_price(etf_code):
    """抓取最新報價"""
    try:
        ticker = yf.Ticker(etf_code)
        
        # 嘗試快速資訊
        fast_info = getattr(ticker, "fast_info", None)
        if fast_info:
            for key in ("last_price", "lastPrice", "regularMarketPrice"):
                price = fast_info.get(key)
                if price and price > 0:
                    return float(price)
        
        # 回退到歷史資料
        hist = ticker.history(period="5d")
        if not hist.empty and 'Close' in hist.columns:
            return float(hist['Close'].iloc[-1])
        
        return None
    except:
        return None


@st.cache_data(ttl=7200)
def fetch_dividend_info(etf_code):
    """抓取配息資訊（優先 FinMind，備用靜態資料）"""
    stock_code = etf_code.replace('.TW', '')
    
    # 方法 1: FinMind API
    try:
        url = "https://api.finmindtrade.com/api/v4/data"
        params = {
            "dataset": "TaiwanStockDividend",
            "data_id": stock_code,
            "start_date": (datetime.now() - timedelta(days=400)).strftime('%Y-%m-%d'),
            "token": ""
        }
        
        response = requests.get(url, params=params, timeout=10)
        
        if response.status_code == 200:
            data = response.json()
            
            if data.get('status') == 200 and data.get('data'):
                df = pd.DataFrame(data['data'])
                
                if not df.empty:
                    # 處理日期
                    date_col = 'date' if 'date' in df.columns else 'ex_dividend_date'
                    df[date_col] = pd.to_datetime(df[date_col])
                    df = df.sort_values(date_col, ascending=False)
                    
                    # 處理配息金額
                    div_col = None
                    for col in ['cash_dividend', 'CashDividend', 'cash_dividend_amount']:
                        if col in df.columns:
                            div_col = col
                            break
                    
                    if div_col:
                        df[div_col] = pd.to_numeric(df[div_col], errors='coerce')
                        df = df[df[div_col] > 0].dropna(subset=[div_col])
                        
                        if not df.empty:
                            # 計算 TTM
                            one_year_ago = datetime.now() - timedelta(days=365)
                            ttm_df = df[df[date_col] >= one_year_ago]
                            ttm_sum = ttm_df[div_col].sum()
                            
                            # 取得最新價格計算殖利率
                            latest_price = fetch_latest_price(etf_code)
                            if not latest_price or latest_price <= 0:
                                latest_price = 100
                            
                            ttm_yield = (ttm_sum / latest_price * 100) if latest_price > 0 else 0
                            
                            return {
                                "最新配息日": df.iloc[0][date_col].date(),
                                "最近一次配息": round(float(df.iloc[0][div_col]), 3),
                                "TTM配息": round(float(ttm_sum), 3),
                                "TTM殖利率%": round(ttm_yield, 2),
                                "資料來源": "FinMind API"
                            }
    except:
        pass
    
    # 方法 2: 靜態資料（備用）
    static_data = {
        "0050": {"配息": 5.50, "殖利率": 3.2, "日期": "2024-07-22"},
        "0056": {"配息": 4.20, "殖利率": 6.5, "日期": "2025-01-22"},
        "006208": {"配息": 1.30, "殖利率": 2.9, "日期": "2024-07-22"},
        "00878": {"配息": 1.52, "殖利率": 7.2, "日期": "2024-11-22"},
        "00919": {"配息": 2.32, "殖利率": 9.1, "日期": "2025-01-22"},
        "00692": {"配息": 0.96, "殖利率": 3.1, "日期": "2024-07-22"},
        "00757": {"配息": 0.56, "殖利率": 2.5, "日期": "2024-08-22"},
        "00929": {"配息": 1.80, "殖利率": 8.5, "日期": "2025-01-22"}
    }
    
    if stock_code in static_data:
        d = static_data[stock_code]
        return {
            "最新配息日": datetime.strptime(d["日期"], "%Y-%m-%d").date(),
            "最近一次配息": d["配息"] / 4,  # 假設季配
            "TTM配息": d["配息"],
            "TTM殖利率%": d["殖利率"],
            "資料來源": "靜態資料"
        }
    
    return {
        "最新配息日": None,
        "最近一次配息": 0.0,
        "TTM配息": 0.0,
        "TTM殖利率%": 0.0,
        "資料來源": "無資料"
    }


def calculate_metrics(price_df, market_df):
    """計算財務指標"""
    returns = price_df["Close"].pct_change().dropna()
    market_returns = market_df["Close"].pct_change().dropna()
    
    # 對齊日期
    common_idx = returns.index.intersection(market_returns.index)
    returns = returns.loc[common_idx]
    market_returns = market_returns.loc[common_idx]
    
    # 年化指標
    ann_return = returns.mean() * TRADING_DAYS * 100
    ann_vol = returns.std() * np.sqrt(TRADING_DAYS) * 100
    sharpe = (ann_return/100 - RISK_FREE_RATE) / (ann_vol/100) if ann_vol > 0 else 0
    
    # Beta
    beta = np.cov(returns, market_returns)[0, 1] / np.var(market_returns, ddof=1)
    
    # 最大回撤
    cumulative = (1 + returns).cumprod()
    running_max = cumulative.expanding().max()
    drawdown = (cumulative - running_max) / running_max
    max_dd = drawdown.min() * 100
    
    return {
        "年化報酬%": round(ann_return, 2),
        "年化波動%": round(ann_vol, 2),
        "Sharpe": round(sharpe, 2),
        "Beta": round(beta, 2),
        "最大回撤%": round(max_dd, 2)
    }


# ===============================
# 主要資料處理
# ===============================

if not selected_etfs:
    st.warning("請至少選擇一檔 ETF")
    st.stop()

# 載入市場基準
with st.spinner("載入市場基準資料..."):
    market_df = fetch_price_data(MARKET_BENCHMARK)
    
if market_df is None:
    st.error("❌ 無法載入市場基準（0050）資料")
    st.stop()

# 載入所有選定的 ETF
progress_bar = st.progress(0)
status_text = st.empty()

etf_data = []

for i, etf_code in enumerate(selected_etfs):
    status_text.text(f"載入 {etf_code} ({i+1}/{len(selected_etfs)})")
    
    # 價格資料
    price_df = fetch_price_data(etf_code)
    if price_df is None:
        progress_bar.progress((i + 1) / len(selected_etfs))
        continue
    
    # 最新報價
    latest_price = fetch_latest_price(etf_code)
    if not latest_price:
        latest_price = float(price_df['Close'].iloc[-1])
    
    # 成交量
    latest_volume = int(price_df['Volume'].iloc[-1])
    avg_volume = int(price_df['Volume'].rolling(20).mean().iloc[-1])
    
    # 計算指標
    metrics = calculate_metrics(price_df, market_df)
    
    # 配息資訊
    div_info = fetch_dividend_info(etf_code)
    
    # 組合資料
    row = {
        "ETF代碼": etf_code.replace('.TW', ''),
        "ETF名稱": ETF_LIST[etf_code],
        "最新價": latest_price,
        "當日成交量": latest_volume,
        "20日均量": avg_volume,
        **metrics,
        **div_info
    }
    
    etf_data.append(row)
    progress_bar.progress((i + 1) / len(selected_etfs))

progress_bar.empty()
status_text.empty()

if not etf_data:
    st.error("❌ 無法載入任何 ETF 資料")
    st.stop()

df = pd.DataFrame(etf_data)

# ===============================
# 排序邏輯
# ===============================
sort_mapping = {
    "Sharpe Ratio": ("Sharpe", False),
    "年化報酬率": ("年化報酬%", False),
    "TTM 殖利率": ("TTM殖利率%", False),
    "成交量": ("當日成交量", False),
    "最新價": ("最新價", False)
}

sort_col, ascending = sort_mapping[sort_option]
df_sorted = df.sort_values(sort_col, ascending=ascending)

# ===============================
# 顯示 Top N 表格
# ===============================
st.subheader(f"🏆 Top {top_n} ETF（按 {sort_option} 排序）")

display_cols = [
    "ETF代碼", "ETF名稱", "最新價", "年化報酬%", "年化波動%",
    "Sharpe", "Beta", "TTM殖利率%", "最新配息日", "TTM配息"
]

st.dataframe(
    df_sorted.head(top_n)[display_cols].style.format({
        "最新價": "{:.2f}",
        "年化報酬%": "{:.2f}%",
        "年化波動%": "{:.2f}%",
        "Sharpe": "{:.2f}",
        "Beta": "{:.2f}",
        "TTM殖利率%": "{:.2f}%",
        "TTM配息": "{:.3f}"
    }).background_gradient(subset=["年化報酬%"], cmap="RdYlGn"),
    use_container_width=True
)

# ===============================
# 關鍵指標卡片
# ===============================
st.markdown("---")
st.subheader("📊 關鍵指標")

col1, col2, col3, col4 = st.columns(4)

with col1:
    best_return = df_sorted.iloc[0]
    st.metric(
        "🥇 最佳報酬",
        f"{best_return['ETF代碼']}",
        f"{best_return['年化報酬%']:.2f}%"
    )

with col2:
    best_sharpe = df.sort_values("Sharpe", ascending=False).iloc[0]
    st.metric(
        "⭐ 最佳 Sharpe",
        f"{best_sharpe['ETF代碼']}",
        f"{best_sharpe['Sharpe']:.2f}"
    )

with col3:
    best_yield = df.sort_values("TTM殖利率%", ascending=False).iloc[0]
    st.metric(
        "💰 最高殖利率",
        f"{best_yield['ETF代碼']}",
        f"{best_yield['TTM殖利率%']:.2f}%"
    )

with col4:
    most_stable = df.sort_values("年化波動%").iloc[0]
    st.metric(
        "🛡️ 最穩定",
        f"{most_stable['ETF代碼']}",
        f"波動 {most_stable['年化波動%']:.2f}%"
    )

# ===============================
# 雷達圖
# ===============================
st.markdown("---")
st.subheader(f"🕸️ 多維度績效雷達圖（Top {min(top_n, 5)}）")

# 準備雷達圖資料
radar_df = df_sorted.head(min(top_n, 5)).copy()

# 標準化指標（0-1 範圍）
metrics_to_normalize = ["年化報酬%", "Sharpe", "TTM殖利率%"]
for col in metrics_to_normalize:
    min_val = radar_df[col].min()
    max_val = radar_df[col].max()
    if max_val > min_val:
        radar_df[f"{col}_norm"] = (radar_df[col] - min_val) / (max_val - min_val)
    else:
        radar_df[f"{col}_norm"] = 0.5

# 波動率反向標準化（低波動 = 高分）
vol_min = radar_df["年化波動%"].min()
vol_max = radar_df["年化波動%"].max()
if vol_max > vol_min:
    radar_df["穩定性_norm"] = 1 - (radar_df["年化波動%"] - vol_min) / (vol_max - vol_min)
else:
    radar_df["穩定性_norm"] = 0.5

# 建立雷達圖
fig_radar = go.Figure()

radar_labels = ["報酬率", "風險調整報酬", "殖利率", "穩定性"]

for _, row in radar_df.iterrows():
    values = [
        row["年化報酬%_norm"],
        row["Sharpe_norm"],
        row["TTM殖利率%_norm"],
        row["穩定性_norm"]
    ]
    values.append(values[0])  # 閉合
    
    fig_radar.add_trace(go.Scatterpolar(
        r=values,
        theta=radar_labels + [radar_labels[0]],
        fill='toself',
        name=row['ETF代碼'],
        opacity=0.6
    ))

fig_radar.update_layout(
    polar=dict(
        radialaxis=dict(
            visible=True,
            range=[0, 1]
        )
    ),
    showlegend=True,
    height=500
)

st.plotly_chart(fig_radar, use_container_width=True)

# ===============================
# 氣泡圖
# ===============================
st.markdown("---")
st.subheader("💭 風險報酬分析圖")

bubble_chart = alt.Chart(df_sorted.head(top_n)).mark_circle(opacity=0.7).encode(
    x=alt.X('年化報酬%:Q', title='年化報酬率 (%)', scale=alt.Scale(zero=False)),
    y=alt.Y('年化波動%:Q', title='年化波動率 (%)', scale=alt.Scale(zero=False)),
    size=alt.Size('TTM殖利率%:Q', title='TTM 殖利率 (%)', scale=alt.Scale(range=[100, 2000])),
    color=alt.Color('Sharpe:Q', title='Sharpe Ratio', scale=alt.Scale(scheme='viridis')),
    tooltip=[
        alt.Tooltip('ETF代碼', title='ETF'),
        alt.Tooltip('ETF名稱', title='名稱'),
        alt.Tooltip('年化報酬%', title='年化報酬', format='.2f'),
        alt.Tooltip('年化波動%', title='年化波動', format='.2f'),
        alt.Tooltip('Sharpe', title='Sharpe Ratio', format='.2f'),
        alt.Tooltip('TTM殖利率%', title='殖利率', format='.2f')
    ]
).properties(
    height=500
).interactive()

st.altair_chart(bubble_chart, use_container_width=True)

# ===============================
# 完整比較表
# ===============================
st.markdown("---")
st.subheader("📋 完整 ETF 比較")

all_cols = [
    "ETF代碼", "ETF名稱", "最新價", "年化報酬%", "年化波動%",
    "Sharpe", "Beta", "最大回撤%", "TTM殖利率%",
    "當日成交量", "20日均量", "資料來源"
]

st.dataframe(
    df_sorted[all_cols].style.format({
        "最新價": "{:.2f}",
        "年化報酬%": "{:.2f}%",
        "年化波動%": "{:.2f}%",
        "Sharpe": "{:.2f}",
        "Beta": "{:.2f}",
        "最大回撤%": "{:.2f}%",
        "TTM殖利率%": "{:.2f}%",
        "當日成交量": "{:,.0f}",
        "20日均量": "{:,.0f}"
    }),
    use_container_width=True
)

# ===============================
# 頁尾說明
# ===============================
st.markdown("---")
st.caption(
    "📡 **資料來源**：Yahoo Finance (價格), FinMind API (配息) | "
    "⏰ **更新頻率**：價格 30 分鐘, 配息 2 小時 | "
    "⚠️ **免責聲明**：本系統僅供參考，不構成投資建議"
)

with st.expander("📖 使用說明"):
    st.markdown("""
    **功能說明：**
    - **即時報價**：顯示最新價格與成交量
    - **配息資訊**：TTM（過去 12 個月）配息與殖利率
    - **績效指標**：年化報酬、波動率、Sharpe Ratio、Beta、最大回撤
    - **雷達圖**：多維度指標視覺化比較
    - **氣泡圖**：風險報酬關係，泡泡大小代表殖利率
    
    **排序選項：**
    - Sharpe Ratio：風險調整後報酬（綜合指標）
    - 年化報酬率：純報酬表現
    - TTM 殖利率：現金流收益
    - 成交量：市場流動性
    
    **資料限制：**
    - Yahoo Finance 可能延遲 15 分鐘
    - FinMind 免費版更新較慢
    - 建議搭配券商報價使用
    """)
